### Пример:

#["Название События"]
#
### Категория события
# category = "Категория События"
#
# ### Описание события
# description = "Описание события..."
#
# ### Вес этого события в процессе случайного выбора
# ### Более высокие веса имеют больше шансов быть выбранными
# ### 10 - вес по умолчанию. 20 - в два раза более вероятно; 5 - в два раза менее вероятно, чем по умолчанию
# ### 0 здесь НЕ отключает событие, просто делает его крайне маловероятным
# weight = 10
#
# ### Самое раннее world.time, когда событие может начаться (длительность раунда в децисекундах)
# ### по умолчанию: 12000 децисекунд (20 минут)
# earliest_start = 12000
#
# ### Минимальное количество живых, не-AFK игроков-людей на сервере, необходимое для запуска события
# min_players = 0
#
# ### Максимальное количество раз, которое это событие может произойти (естественным образом), его всё ещё можно принудительно запустить
# ### Установив это значение в 0, вы можете эффективно отключить событие
# max_occurrences = 20
#
# ### Строка, которая должна быть в списке SSgamemode.holidays, если вы хотите, чтобы это событие было привязано к празднику
# ### всё с (не-null) holidayID, которое не совпадает с holiday, не может запуститься
# ### Не уверен, используется ли это подсистемой `Gamemode`
# holidayID = "ИдентификаторПраздника"
#
# ### Это событие волшебника?
# wizardevent = false
#
# ### Должны ли мы уведомить призраков о запуске этого события
# ### Следует отключать на событиях, которые запускаются часто
# alert_observers = true
#
# ### Минимальное количество ритуалов волшебника для запуска этого события, включительно.
# ### -1 - никогда не запускается
# ### 0-7 - допустимые стадии ритуалов
# min_wizard_trigger_potency = -1
#
# ### Максимальное количество ритуалов волшебника для запуска этого события, включительно.
# ### -1 - никогда не запускается
# ### 0-7 - допустимые стадии ритуалов
# max_wizard_trigger_potency = -1
#
# ### Флаги, определяющие, должно ли это событие запускаться на определённых типах карт
# ### Возможные значения:
# ### - 0 - Событие не имеет специальных требований
# ### - 1 - Событие может запускаться только на карте в космосе
# ### - 2 - Событие может запускаться только на карте, которая является планетой
# map_flags = 0
#
# ### Какой трек использует это событие в системе рассказчика
# ### Возможные значения:
# ### - "Mundane"
# ### - "Moderate"
# ### - "Major"
# ### - "Roleset"
# track = "Moderate"
#
# ### Коэффициент уменьшения веса события за каждое повторение
# ### 1 - означает, что вес не будет уменьшаться
# reoccurence_penalty_multiplier = 1
#
# ### Список тегов, определяющих тип события. По умолчанию пуст - нет тегов.
# ### Возможные значения:
# ###	- "combat" - Когда событие ориентировано на бой (спавн монстров, изначально враждебные антагонисты)
# ###	- "spooky" - Когда событие жуткое (сломанные огни, некоторые антагонисты)
# ###	- "destructive" - Когда событие разрушительно в значительной степени (метеоры, блоб)
# ###	- "communal" - Когда событие затрагивает большинство членов экипажа в некоторой степени (отключение связи)
# ###	- "targeted" - Когда событие нацелено на конкретного человека (аппендицит, сердечный приступ)
# ###	- "positive" - Когда событие положительное и помогает экипажу в некоторой степени (Аренда Шаттла, Грузовой Пода)
# ###	- "crew_antag" - Когда один из членов экипажа становится антагонистом
# ###	- "team_antag" - Когда событие антагониста сосредоточено на командном взаимодействии.
# ###	- "away_antag" - Когда один из игроков, не являющихся членами экипажа, становится антагонистом
# ###	- "overmap" - Когда событие затрагивает оверкарту
# ###	- "space" - Когда событие требует, чтобы станция была в космосе (метеоры, карпы)
# ###	- "planetary" - Когда событие требует, чтобы станция была планетарной.
# ###	- "external" - Когда событие является внешней угрозой (метеоры, ядерные оперативники).
# ###	- "alien" - Когда событие является инопланетной угрозой (блоб, ксеносы)
# ###	- "magical" - Когда событие магической природы
# tags = []
#
# ### Список отделов и требуемого количества crew. Ключ - id отдела, значение - требуемое количество crew (целое число).
# ### По умолчанию пуст - нет специальных требований к отделам
# ### Возможные ключи:
# ### - "head"
# ### - "med"
# ### - "eng"
# ### - "rnd"
# ### - "sec"
# req_departments_crew = []
#
# ### Список отделов и требуемой мощности. Ключ - id отдела, значение - требуемая мощность (целое число).
# ### По умолчанию пуст - нет специальных требований к отделам
# ### Возможные ключи:
# ### - "head"
# ### - "med"
# ### - "eng"
# ### - "rnd"
# ### - "sec"
# req_departments_power = []
